export const mockData = {
  categories: [
    { title: "Bebidas", description: "Todo tipo de bebidas", imageUrl: "", href: "#", stock: 100 },
    { title: "Snacks", description: "Aperitivos y picadas", imageUrl: "", href: "#", stock: 80 },
    { title: "Lácteos", description: "Productos de leche y derivados", imageUrl: "", href: "#", stock: 50 },
    { title: "Carnes", description: "Carnes frescas y congeladas", imageUrl: "", href: "#", stock: 40 },
    { title: "Verduras", description: "Verduras frescas del día", imageUrl: "", href: "#", stock: 70 },
    { title: "Frutas", description: "Frutas frescas y tropicales", imageUrl: "", href: "#", stock: 90 },
    { title: "Limpieza", description: "Productos para el hogar", imageUrl: "", href: "#", stock: 60 }
  ],
  products: [
    { id: 1, title: "Coca-Cola 500ml", description: "Refresco de cola", imageUrl: "/products/coca-cola.png", href: "#", productCode: "SKU-001", stock: 30, category: "Bebidas" },
    { id: 2, title: "Pepsi 500ml", description: "Refresco de cola", imageUrl: "", href: "#", productCode: "SKU-002", stock: 25, category: "Bebidas" },
    { id: 3, title: "Agua Mineral 1L", description: "Agua pura sin gas", imageUrl: "", href: "#", productCode: "SKU-003", stock: 50, category: "Bebidas" },
    { id: 4, title: "Jugo de Naranja 1L", description: "Jugo natural", imageUrl: "", href: "#", productCode: "SKU-004", stock: 20, category: "Bebidas" },
    { id: 5, title: "Energizante Red Bull", description: "Bebida energética", imageUrl: "", href: "#", productCode: "SKU-005", stock: 15, category: "Bebidas" },
    { id: 6, title: "Fernet Branca 750ml", description: "Bebida alcohólica", imageUrl: "", href: "#", productCode: "SKU-006", stock: 40, category: "Bebidas" },
    { id: 7, title: "Cerveza Heineken 330ml", description: "Cerveza de malta", imageUrl: "", href: "#", productCode: "SKU-007", stock: 60, category: "Bebidas" },
    { id: 8, title: "Cerveza Corona 355ml", description: "Cerveza estilo lager", imageUrl: "", href: "#", productCode: "SKU-008", stock: 50, category: "Bebidas" },
    { id: 9, title: "Jugo de Manzana 1L", description: "Jugo natural de manzana", imageUrl: "", href: "#", productCode: "SKU-009", stock: 30, category: "Bebidas" },
    { id: 10, title: "Sprite 500ml", description: "Refresco sabor limón", imageUrl: "", href: "#", productCode: "SKU-010", stock: 35, category: "Bebidas" },

    { id: 11, title: "Papas Fritas Lay's", description: "Papas fritas clásicas", imageUrl: "", href: "#", productCode: "SKU-011", stock: 40, category: "Snacks" },
    { id: 12, title: "Tortillas Doritos", description: "Tortillas de maíz con sabor", imageUrl: "", href: "#", productCode: "SKU-012", stock: 50, category: "Snacks" },
    { id: 13, title: "Galletas Oreo", description: "Galletas rellenas con crema", imageUrl: "", href: "#", productCode: "SKU-013", stock: 70, category: "Snacks" },
    { id: 14, title: "Chocolate Milka", description: "Chocolate de leche", imageUrl: "", href: "#", productCode: "SKU-014", stock: 60, category: "Snacks" },
    { id: 15, title: "Almendras con Chocolate", description: "Almendras cubiertas de chocolate", imageUrl: "", href: "#", productCode: "SKU-015", stock: 30, category: "Snacks" },
    { id: 16, title: "Galletas Chips Ahoy", description: "Galletas con chips de chocolate", imageUrl: "", href: "#", productCode: "SKU-016", stock: 50, category: "Snacks" },
    { id: 17, title: "Mix de Frutos Secos", description: "Frutos secos variados", imageUrl: "", href: "#", productCode: "SKU-017", stock: 40, category: "Snacks" },
    { id: 18, title: "Palitos Salados", description: "Palitos de pan salados", imageUrl: "", href: "#", productCode: "SKU-018", stock: 60, category: "Snacks" },
    { id: 19, title: "Cacahuetes", description: "Cacahuetes tostados", imageUrl: "", href: "#", productCode: "SKU-019", stock: 50, category: "Snacks" },
    { id: 20, title: "Pretzels", description: "Pretzels salados", imageUrl: "", href: "#", productCode: "SKU-020", stock: 70, category: "Snacks" },

    { id: 21, title: "Leche Entera 1L", description: "Leche de vaca", imageUrl: "", href: "#", productCode: "SKU-021", stock: 50, category: "Lácteos" },
    { id: 22, title: "Yogur Natural 500g", description: "Yogur sin sabor", imageUrl: "", href: "#", productCode: "SKU-022", stock: 40, category: "Lácteos" },
    { id: 23, title: "Queso Crema 200g", description: "Queso cremoso", imageUrl: "", href: "#", productCode: "SKU-023", stock: 60, category: "Lácteos" },
    { id: 24, title: "Manteca 200g", description: "Manteca de cerdo", imageUrl: "", href: "#", productCode: "SKU-024", stock: 30, category: "Lácteos" },
    { id: 25, title: "Crema de Leche 1L", description: "Crema de leche líquida", imageUrl: "", href: "#", productCode: "SKU-025", stock: 50, category: "Lácteos" },
    { id: 26, title: "Leche Condensada 400g", description: "Leche condensada", imageUrl: "", href: "#", productCode: "SKU-026", stock: 40, category: "Lácteos" },
    { id: 27, title: "Yogur Griego 500g", description: "Yogur griego", imageUrl: "", href: "#", productCode: "SKU-027", stock: 30, category: "Lácteos" },
    { id: 28, title: "Queso Parmesano 150g", description: "Queso parmesano rallado", imageUrl: "", href: "#", productCode: "SKU-028", stock: 20, category: "Lácteos" },
    { id: 29, title: "Leche de Almendra 1L", description: "Leche vegetal", imageUrl: "", href: "#", productCode: "SKU-029", stock: 25, category: "Lácteos" },
    { id: 30, title: "Ricotta 500g", description: "Queso ricotta", imageUrl: "", href: "#", productCode: "SKU-030", stock: 35, category: "Lácteos" },

    { id: 31, title: "Carne de Res 1kg", description: "Carne fresca de res", imageUrl: "", href: "#", productCode: "SKU-031", stock: 40, category: "Carnes" },
    { id: 32, title: "Pechuga de Pollo 500g", description: "Pechuga de pollo fresca", imageUrl: "", href: "#", productCode: "SKU-032", stock: 30, category: "Carnes" },
    { id: 33, title: "Panceta 500g", description: "Panceta curada", imageUrl: "", href: "#", productCode: "SKU-033", stock: 50, category: "Carnes" },
    { id: 34, title: "Costillas de Cerdo 1kg", description: "Costillas frescas de cerdo", imageUrl: "", href: "#", productCode: "SKU-034", stock: 60, category: "Carnes" },
    { id: 35, title: "Chorizos 500g", description: "Chorizos frescos", imageUrl: "", href: "#", productCode: "SKU-035", stock: 20, category: "Carnes" },
    { id: 36, title: "Morcilla 500g", description: "Morcilla de cerdo", imageUrl: "", href: "#", productCode: "SKU-036", stock: 40, category: "Carnes" },
    { id: 37, title: "Pechuga de Pavo 500g", description: "Pechuga de pavo fresca", imageUrl: "", href: "#", productCode: "SKU-037", stock: 30, category: "Carnes" },
    { id: 38, title: "Bife de Chorizo 1kg", description: "Bife de chorizo de res", imageUrl: "", href: "#", productCode: "SKU-038", stock: 25, category: "Carnes" },
    { id: 39, title: "Filete de Salmón 500g", description: "Filete fresco de salmón", imageUrl: "", href: "#", productCode: "SKU-039", stock: 35, category: "Carnes" },
    { id: 40, title: "Filete de Merluza 500g", description: "Filete fresco de merluza", imageUrl: "", href: "#", productCode: "SKU-040", stock: 20, category: "Carnes" },

    { id: 41, title: "Tomates", description: "Tomates frescos", imageUrl: "", href: "#", productCode: "SKU-041", stock: 50, category: "Verduras" },
    { id: 42, title: "Lechuga", description: "Lechuga fresca", imageUrl: "", href: "#", productCode: "SKU-042", stock: 60, category: "Verduras" },
    { id: 43, title: "Cebollas", description: "Cebollas frescas", imageUrl: "", href: "#", productCode: "SKU-043", stock: 70, category: "Verduras" },
    { id: 44, title: "Pepinos", description: "Pepinos frescos", imageUrl: "", href: "#", productCode: "SKU-044", stock: 80, category: "Verduras" },
    { id: 45, title: "Ajo", description: "Ajo fresco", imageUrl: "", href: "#", productCode: "SKU-045", stock: 60, category: "Verduras" },
    { id: 46, title: "Espinacas", description: "Espinacas frescas", imageUrl: "", href: "#", productCode: "SKU-046", stock: 50, category: "Verduras" },
    { id: 47, title: "Pimientos", description: "Pimientos frescos", imageUrl: "", href: "#", productCode: "SKU-047", stock: 40, category: "Verduras" },
    { id: 48, title: "Zanahorias", description: "Zanahorias frescas", imageUrl: "", href: "#", productCode: "SKU-048", stock: 50, category: "Verduras" },
    { id: 49, title: "Berenjenas", description: "Berenjenas frescas", imageUrl: "", href: "#", productCode: "SKU-049", stock: 30, category: "Verduras" },
    { id: 50, title: "Calabacines", description: "Calabacines frescos", imageUrl: "", href: "#", productCode: "SKU-050", stock: 60, category: "Verduras" },

    { id: 51, title: "Manzanas", description: "Manzanas frescas", imageUrl: "", href: "#", productCode: "SKU-051", stock: 50, category: "Frutas" },
    { id: 52, title: "Plátanos", description: "Plátanos frescos", imageUrl: "", href: "#", productCode: "SKU-052", stock: 40, category: "Frutas" },
    { id: 53, title: "Peras", description: "Peras frescas", imageUrl: "", href: "#", productCode: "SKU-053", stock: 60, category: "Frutas" },
    { id: 54, title: "Naranjas", description: "Naranjas frescas", imageUrl: "", href: "#", productCode: "SKU-054", stock: 70, category: "Frutas" },
    { id: 55, title: "Uvas", description: "Uvas frescas", imageUrl: "", href: "#", productCode: "SKU-055", stock: 60, category: "Frutas" },
    { id: 56, title: "Fresas", description: "Fresas frescas", imageUrl: "", href: "#", productCode: "SKU-056", stock: 80, category: "Frutas" },
    { id: 57, title: "Kiwis", description: "Kiwis frescos", imageUrl: "", href: "#", productCode: "SKU-057", stock: 50, category: "Frutas" },
    { id: 58, title: "Mangos", description: "Mangos frescos", imageUrl: "", href: "#", productCode: "SKU-058", stock: 40, category: "Frutas" },
    { id: 59, title: "Sandías", description: "Sandías frescas", imageUrl: "", href: "#", productCode: "SKU-059", stock: 30, category: "Frutas" },
    { id: 60, title: "Melones", description: "Melones frescos", imageUrl: "", href: "#", productCode: "SKU-060", stock: 20, category: "Frutas" },

    { id: 61, title: "Detergente Líquido 1L", description: "Detergente para ropa", imageUrl: "", href: "#", productCode: "SKU-061", stock: 30, category: "Limpieza" },
    { id: 62, title: "Jabón Líquido 500ml", description: "Jabón para lavar platos", imageUrl: "", href: "#", productCode: "SKU-062", stock: 50, category: "Limpieza" },
    { id: 63, title: "Limpiador Multiuso 500ml", description: "Limpiador multiuso", imageUrl: "", href: "#", productCode: "SKU-063", stock: 40, category: "Limpieza" },
    { id: 64, title: "Cloro 1L", description: "Cloro para desinfectar", imageUrl: "", href: "#", productCode: "SKU-064", stock: 35, category: "Limpieza" },
    { id: 65, title: "Suavizante de Ropa 1L", description: "Suavizante para la ropa", imageUrl: "", href: "#", productCode: "SKU-065", stock: 50, category: "Limpieza" },
    { id: 66, title: "Desinfectante 500ml", description: "Desinfectante de superficies", imageUrl: "", href: "#", productCode: "SKU-066", stock: 45, category: "Limpieza" },
    { id: 67, title: "Papel Higiénico 12 rollos", description: "Papel higiénico suave", imageUrl: "", href: "#", productCode: "SKU-067", stock: 70, category: "Limpieza" },
    { id: 68, title: "Toallitas Desinfectantes", description: "Toallitas limpiadoras", imageUrl: "", href: "#", productCode: "SKU-068", stock: 40, category: "Limpieza" },
    { id: 69, title: "Esponja para Cocina", description: "Esponja para lavar platos", imageUrl: "", href: "#", productCode: "SKU-069", stock: 60, category: "Limpieza" },
    { id: 70, title: "Ambientador", description: "Ambientador para el hogar", imageUrl: "", href: "#", productCode: "SKU-070", stock: 50, category: "Limpieza" },
  ]
};
